apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-configmap
data:
  DB_NAME: "coworkingdatabase"
  DB_USER: "coworkinguser"
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: coworking-secret
type: Opaque
data:
  DB_PASSWORD: "Y293b3JraW5ncGFzc3dvcmQ="
